modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/demistorm/VR-Throwing-Extensions/issues"
license = "GPL-3.0"

[[mods]]
modId = "vr_throwing_extensions"
version = "${version}"
displayName = "VR Throwing Extensions"
displayURL = "https://modrinth.com/mod/vr-throwing-extensions"
logoFile = "vte-static-logo.png"
authors = "Halfstorm"
description = '''
Allows VR players to physically throw weapons and items!

Support me on Ko-Fi: https://ko-fi.com/hstorm

Discord: https://discord.gg/7uttzPbTGq

Requires Vivecraft mod.
'''

[[dependencies.vr_throwing_extensions]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_throwing_extensions]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_throwing_extensions]]
modId = "vivecraft"
mandatory = true
versionRange = "[1.3.3,)"
ordering = "AFTER"
side = "BOTH"