name: Publish Mod

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Read versions from gradle.properties
        id: version
        run: |
          echo "mod_version=$(grep 'mod_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT
          echo "minecraft_version=$(grep 'minecraft_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      
      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: SDTJzC3Z
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1374432
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version: ${{ steps.version.outputs.mod_version }}-fabric
          name: VR Throwing Extensions (Fabric ${{ steps.version.outputs.minecraft_version }}-${{ steps.version.outputs.mod_version }})
          files: fabric/build/libs/!(*-@(sources|javadoc|dev|shadow)).jar
          loaders: fabric
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md

      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: SDTJzC3Z
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1374432
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version: ${{ steps.version.outputs.mod_version }}-forge
          name: VR Throwing Extensions (Forge ${{ steps.version.outputs.minecraft_version }}-${{ steps.version.outputs.mod_version }})
          files: forge/build/libs/!(*-@(sources|javadoc|dev|shadow)).jar
          loaders: forge
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
